language: php
php:
  - 5.4
  - 5.5

script: vendor/bin/codecept run --coverage-xml

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install
  - composer create-project --prefer-source fuel/fuel:dev-1.8/develop /tmp/fuel

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
